version: "3.9"
services: 
  varnish:
    build: ./varnish
    command:
      - -p
      - vcc_allow_inline_c=on
    depends_on: 
      - apache
  apache:
    build: ./apache
    volumes: 
      - ./web:/var/www/html
    ports:
      - "443:443"
      - "80:80"
    depends_on: 
      - php-fpm
      - mysql
      - redis
      - elasticsearch
  php-fpm:
    build: ./php-fpm
    environment: 
      - OPCACHE_REVALIDATE=${OPCACHE_REVALIDATE}
      - COMPOSER_MEMORY_LIMIT=-1
    volumes: 
      - ./web:/var/www/html
    ports: 
      - "9000:9001"
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: voyage
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/data:/var/lib/mysql
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
  elasticsearch:
    image: elasticsearch:7.10.1
    environment: 
      - "discovery.type=single-node"
    ports:
      - 9200:9200
      - 9300:9300
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql